package com.mivim.data.dao;

import com.mivim.data.model.Itemcategory;
import com.mivim.data.model.ItemcategoryExample;
import com.mivim.data.model.ItemcategoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemcategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    long countByExample(ItemcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int deleteByExample(ItemcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int deleteByPrimaryKey(ItemcategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int insert(Itemcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int insertSelective(Itemcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    List<Itemcategory> selectByExample(ItemcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    Itemcategory selectByPrimaryKey(ItemcategoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByExampleSelective(@Param("record") Itemcategory record, @Param("example") ItemcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByExample(@Param("record") Itemcategory record, @Param("example") ItemcategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByPrimaryKeySelective(Itemcategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemcategory
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByPrimaryKey(Itemcategory record);
}