package com.mivim.data.dao;

import com.mivim.data.model.Shippingaddress;
import com.mivim.data.model.ShippingaddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShippingaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    long countByExample(ShippingaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int deleteByExample(ShippingaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int insert(Shippingaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int insertSelective(Shippingaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    List<Shippingaddress> selectByExample(ShippingaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    Shippingaddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByExampleSelective(@Param("record") Shippingaddress record, @Param("example") ShippingaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByExample(@Param("record") Shippingaddress record, @Param("example") ShippingaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByPrimaryKeySelective(Shippingaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippingaddress
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    int updateByPrimaryKey(Shippingaddress record);
}