package com.mivim.data.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.categoryName
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parentId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.categoryName
     *
     * @return the value of category.categoryName
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.categoryName
     *
     * @param categoryName the value for category.categoryName
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parentId
     *
     * @return the value of category.parentId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parentId
     *
     * @param parentId the value for category.parentId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }
}