package com.mivim.data.model;

public class ItemcategoryKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcategory.itemId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemcategory.categoryId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcategory.itemId
     *
     * @return the value of itemcategory.itemId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcategory.itemId
     *
     * @param itemId the value for itemcategory.itemId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemcategory.categoryId
     *
     * @return the value of itemcategory.categoryId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemcategory.categoryId
     *
     * @param categoryId the value for itemcategory.categoryId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }
}