package com.mivim.data.model;

import java.util.ArrayList;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("userId like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("userId not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSubTotalIsNull() {
            addCriterion("subTotal is null");
            return (Criteria) this;
        }

        public Criteria andSubTotalIsNotNull() {
            addCriterion("subTotal is not null");
            return (Criteria) this;
        }

        public Criteria andSubTotalEqualTo(String value) {
            addCriterion("subTotal =", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotEqualTo(String value) {
            addCriterion("subTotal <>", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalGreaterThan(String value) {
            addCriterion("subTotal >", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalGreaterThanOrEqualTo(String value) {
            addCriterion("subTotal >=", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalLessThan(String value) {
            addCriterion("subTotal <", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalLessThanOrEqualTo(String value) {
            addCriterion("subTotal <=", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalLike(String value) {
            addCriterion("subTotal like", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotLike(String value) {
            addCriterion("subTotal not like", value, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalIn(List<String> values) {
            addCriterion("subTotal in", values, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotIn(List<String> values) {
            addCriterion("subTotal not in", values, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalBetween(String value1, String value2) {
            addCriterion("subTotal between", value1, value2, "subTotal");
            return (Criteria) this;
        }

        public Criteria andSubTotalNotBetween(String value1, String value2) {
            addCriterion("subTotal not between", value1, value2, "subTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalIsNull() {
            addCriterion("grandTotal is null");
            return (Criteria) this;
        }

        public Criteria andGrandTotalIsNotNull() {
            addCriterion("grandTotal is not null");
            return (Criteria) this;
        }

        public Criteria andGrandTotalEqualTo(String value) {
            addCriterion("grandTotal =", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalNotEqualTo(String value) {
            addCriterion("grandTotal <>", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalGreaterThan(String value) {
            addCriterion("grandTotal >", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalGreaterThanOrEqualTo(String value) {
            addCriterion("grandTotal >=", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalLessThan(String value) {
            addCriterion("grandTotal <", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalLessThanOrEqualTo(String value) {
            addCriterion("grandTotal <=", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalLike(String value) {
            addCriterion("grandTotal like", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalNotLike(String value) {
            addCriterion("grandTotal not like", value, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalIn(List<String> values) {
            addCriterion("grandTotal in", values, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalNotIn(List<String> values) {
            addCriterion("grandTotal not in", values, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalBetween(String value1, String value2) {
            addCriterion("grandTotal between", value1, value2, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andGrandTotalNotBetween(String value1, String value2) {
            addCriterion("grandTotal not between", value1, value2, "grandTotal");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIsNull() {
            addCriterion("paymentMode is null");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIsNotNull() {
            addCriterion("paymentMode is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentModeEqualTo(String value) {
            addCriterion("paymentMode =", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotEqualTo(String value) {
            addCriterion("paymentMode <>", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeGreaterThan(String value) {
            addCriterion("paymentMode >", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeGreaterThanOrEqualTo(String value) {
            addCriterion("paymentMode >=", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeLessThan(String value) {
            addCriterion("paymentMode <", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeLessThanOrEqualTo(String value) {
            addCriterion("paymentMode <=", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeLike(String value) {
            addCriterion("paymentMode like", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotLike(String value) {
            addCriterion("paymentMode not like", value, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeIn(List<String> values) {
            addCriterion("paymentMode in", values, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotIn(List<String> values) {
            addCriterion("paymentMode not in", values, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeBetween(String value1, String value2) {
            addCriterion("paymentMode between", value1, value2, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andPaymentModeNotBetween(String value1, String value2) {
            addCriterion("paymentMode not between", value1, value2, "paymentMode");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdIsNull() {
            addCriterion("shippingAddressId is null");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdIsNotNull() {
            addCriterion("shippingAddressId is not null");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdEqualTo(String value) {
            addCriterion("shippingAddressId =", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdNotEqualTo(String value) {
            addCriterion("shippingAddressId <>", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdGreaterThan(String value) {
            addCriterion("shippingAddressId >", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdGreaterThanOrEqualTo(String value) {
            addCriterion("shippingAddressId >=", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdLessThan(String value) {
            addCriterion("shippingAddressId <", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdLessThanOrEqualTo(String value) {
            addCriterion("shippingAddressId <=", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdLike(String value) {
            addCriterion("shippingAddressId like", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdNotLike(String value) {
            addCriterion("shippingAddressId not like", value, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdIn(List<String> values) {
            addCriterion("shippingAddressId in", values, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdNotIn(List<String> values) {
            addCriterion("shippingAddressId not in", values, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdBetween(String value1, String value2) {
            addCriterion("shippingAddressId between", value1, value2, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andShippingAddressIdNotBetween(String value1, String value2) {
            addCriterion("shippingAddressId not between", value1, value2, "shippingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdIsNull() {
            addCriterion("billingAddressId is null");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdIsNotNull() {
            addCriterion("billingAddressId is not null");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdEqualTo(String value) {
            addCriterion("billingAddressId =", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdNotEqualTo(String value) {
            addCriterion("billingAddressId <>", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdGreaterThan(String value) {
            addCriterion("billingAddressId >", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdGreaterThanOrEqualTo(String value) {
            addCriterion("billingAddressId >=", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdLessThan(String value) {
            addCriterion("billingAddressId <", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdLessThanOrEqualTo(String value) {
            addCriterion("billingAddressId <=", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdLike(String value) {
            addCriterion("billingAddressId like", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdNotLike(String value) {
            addCriterion("billingAddressId not like", value, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdIn(List<String> values) {
            addCriterion("billingAddressId in", values, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdNotIn(List<String> values) {
            addCriterion("billingAddressId not in", values, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdBetween(String value1, String value2) {
            addCriterion("billingAddressId between", value1, value2, "billingAddressId");
            return (Criteria) this;
        }

        public Criteria andBillingAddressIdNotBetween(String value1, String value2) {
            addCriterion("billingAddressId not between", value1, value2, "billingAddressId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 18 16:00:44 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}