package com.mivim.data.model;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.subTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String subTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.grandTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String grandTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paymentMode
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String paymentMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.shippingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String shippingAddressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.billingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String billingAddressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userId
     *
     * @return the value of orders.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.userId
     *
     * @param userId the value for orders.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.subTotal
     *
     * @return the value of orders.subTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getSubTotal() {
        return subTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.subTotal
     *
     * @param subTotal the value for orders.subTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setSubTotal(String subTotal) {
        this.subTotal = subTotal == null ? null : subTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.grandTotal
     *
     * @return the value of orders.grandTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getGrandTotal() {
        return grandTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.grandTotal
     *
     * @param grandTotal the value for orders.grandTotal
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setGrandTotal(String grandTotal) {
        this.grandTotal = grandTotal == null ? null : grandTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paymentMode
     *
     * @return the value of orders.paymentMode
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paymentMode
     *
     * @param paymentMode the value for orders.paymentMode
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode == null ? null : paymentMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.shippingAddressId
     *
     * @return the value of orders.shippingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getShippingAddressId() {
        return shippingAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.shippingAddressId
     *
     * @param shippingAddressId the value for orders.shippingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setShippingAddressId(String shippingAddressId) {
        this.shippingAddressId = shippingAddressId == null ? null : shippingAddressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.billingAddressId
     *
     * @return the value of orders.billingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getBillingAddressId() {
        return billingAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.billingAddressId
     *
     * @param billingAddressId the value for orders.billingAddressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setBillingAddressId(String billingAddressId) {
        this.billingAddressId = billingAddressId == null ? null : billingAddressId.trim();
    }
}