package com.mivim.data.model;

import java.util.Date;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.description
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.status
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.updatedDate
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role
     *
     * @return the value of roles.role
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role
     *
     * @param role the value for roles.role
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.description
     *
     * @return the value of roles.description
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.description
     *
     * @param description the value for roles.description
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.status
     *
     * @return the value of roles.status
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.status
     *
     * @param status the value for roles.status
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.updatedDate
     *
     * @return the value of roles.updatedDate
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.updatedDate
     *
     * @param updatedDate the value for roles.updatedDate
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}