package com.mivim.data.model;

public class Shippingaddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippingaddress.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippingaddress.addressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippingaddress.id
     *
     * @return the value of shippingaddress.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippingaddress.id
     *
     * @param id the value for shippingaddress.id
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippingaddress.addressId
     *
     * @return the value of shippingaddress.addressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippingaddress.addressId
     *
     * @param addressId the value for shippingaddress.addressId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }
}