package com.mivim.data.model;

public class UserroleKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.roleId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.userId
     *
     * @return the value of userrole.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.userId
     *
     * @param userId the value for userrole.userId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.roleId
     *
     * @return the value of userrole.roleId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.roleId
     *
     * @param roleId the value for userrole.roleId
     *
     * @mbg.generated Tue Jul 18 16:00:44 IST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}